/* ============================================
   따숲 (ddasoop) - verses.js
   성경 구절 60개

   본문 출처: 성경전서 개역한글판 (대한성서공회)
   저작재산권 보호기간이 만료된 판본입니다.
   인격저작권(성명표시권, 동일성유지권)을 지키기 위해
   본문을 수정하지 않고 원문 그대로 인용하며,
   화면에 출처를 함께 표시합니다.

   AI는 이 본문을 생성하거나 수정하지 않습니다.
   AI에게는 theme(주제 한 줄)만 전달합니다.
   ============================================ */

const VERSE_TRANSLATION = "개역한글판";
const VERSE_PUBLISHER = "대한성서공회";

const VERSES = [

  /* ---------- tired : 지쳤을 때 ---------- */
  { id: "v001", category: "tired", reference: "마태복음 11:28",
    text: "수고하고 무거운 짐진 자들아 다 내게로 오라 내가 너희를 쉬게 하리라",
    theme: "지친 사람에게 주어지는 쉼" },
  { id: "v002", category: "tired", reference: "시편 23:1",
    text: "여호와는 나의 목자시니 내게 부족함이 없으리로다",
    theme: "이미 채워져 있음, 더 애쓰지 않아도 됨" },
  { id: "v003", category: "tired", reference: "이사야 40:31",
    text: "오직 여호와를 앙망하는 자는 새 힘을 얻으리니 독수리의 날개치며 올라감 같을 것이요",
    theme: "내 힘이 아니라 밖에서 오는 새 힘" },
  { id: "v004", category: "tired", reference: "시편 34:18",
    text: "여호와는 마음이 상한 자에게 가까이 하시고 중심에 통회하는 자를 구원하시는도다",
    theme: "무너져 있을 때 오히려 더 가까이 있음" },
  { id: "v005", category: "tired", reference: "베드로전서 5:7",
    text: "너희 염려를 다 주께 맡겨 버리라 이는 저가 너희를 권고하심이니라",
    theme: "혼자 다 지고 있지 않아도 됨" },
  { id: "v006", category: "tired", reference: "고린도후서 12:9",
    text: "내 은혜가 네게 족하도다 이는 내 능력이 약한 데서 온전하여짐이라",
    theme: "약함이 실패가 아니라 통로가 됨" },
  { id: "v007", category: "tired", reference: "시편 121:1",
    text: "내가 산을 향하여 눈을 들리라 나의 도움이 어디서 올꼬",
    theme: "고개를 드는 것부터가 시작" },
  { id: "v008", category: "tired", reference: "요한복음 14:27",
    text: "평안을 너희에게 끼치노니 곧 나의 평안을 너희에게 주노라",
    theme: "세상이 주는 것과 다른, 애쓰지 않아도 되는 평안" },
  { id: "v009", category: "tired", reference: "신명기 31:8",
    text: "여호와 그가 네 앞서 행하시며 너와 함께 하사 너를 떠나지 아니하시며 버리지 아니하시리니",
    theme: "앞서 가 있고, 떠나지 않음" },
  { id: "v010", category: "tired", reference: "시편 46:1",
    text: "하나님은 우리의 피난처시요 힘이시니 환난 중에 만날 큰 도움이시라",
    theme: "숨을 곳이 있다는 것" },

  /* ---------- waiting : 기다림 ---------- */
  { id: "v011", category: "waiting", reference: "시편 27:14",
    text: "너는 여호와를 바랄지어다 강하고 담대하며 여호와를 바랄지어다",
    theme: "기다리는 것 자체가 용기" },
  { id: "v012", category: "waiting", reference: "전도서 3:1",
    text: "천하에 범사가 기한이 있고 모든 목적이 이룰 때가 있나니",
    theme: "각자의 때가 따로 있음" },
  { id: "v013", category: "waiting", reference: "야고보서 5:7",
    text: "농부가 땅에서 나는 귀한 열매를 바라고 길이 참아 이른 비와 늦은 비를 기다리나니",
    theme: "자라는 것을 기다리는 농부의 마음" },
  { id: "v014", category: "waiting", reference: "시편 40:1",
    text: "내가 여호와를 기다리고 기다렸더니 귀를 기울이사 나의 부르짖음을 들으셨도다",
    theme: "기다린 시간이 헛되지 않음" },
  { id: "v015", category: "waiting", reference: "갈라디아서 6:9",
    text: "우리가 선을 행하되 낙심하지 말지니 피곤하지 아니하면 때가 이르매 거두리라",
    theme: "지금 안 보여도 때가 되면 거둠" },
  { id: "v016", category: "waiting", reference: "로마서 8:25",
    text: "만일 우리가 보지 못하는 것을 바라면 참음으로 기다릴지니라",
    theme: "아직 안 보이는 것을 바라보는 힘" },
  { id: "v017", category: "waiting", reference: "하박국 2:3",
    text: "비록 더딜지라도 기다리라 지체되지 않고 정녕 응하리라",
    theme: "더딘 것과 안 오는 것은 다름" },
  { id: "v018", category: "waiting", reference: "이사야 30:18",
    text: "그러므로 여호와께서 기다리시나니 이는 너희에게 은혜를 베풀려 하심이요",
    theme: "기다리는 쪽이 나만은 아님" },
  { id: "v019", category: "waiting", reference: "예레미야애가 3:25",
    text: "무릇 기다리는 자에게나 구하는 영혼에게 여호와께서 선을 베푸시는도다",
    theme: "기다림에 주어지는 선함" },
  { id: "v020", category: "waiting", reference: "시편 130:5",
    text: "나 곧 내 영혼이 여호와를 기다리며 내가 그 말씀을 바라는도다",
    theme: "기다림이 곧 붙드는 방식" },

  /* ---------- words : 말과 소통 ---------- */
  { id: "v021", category: "words", reference: "잠언 15:1",
    text: "유순한 대답은 분노를 쉬게 하여도 과격한 말은 노를 격동하느니라",
    theme: "부드러운 한 마디가 가진 힘" },
  { id: "v022", category: "words", reference: "잠언 25:11",
    text: "경우에 합당한 말은 아로새긴 은쟁반에 금사과니라",
    theme: "때에 맞는 말의 귀함" },
  { id: "v023", category: "words", reference: "출애굽기 4:12",
    text: "이제 가라 내가 네 입과 함께 있어서 할 말을 가르치리라",
    theme: "말이 서툴러도 함께해 주심" },
  { id: "v024", category: "words", reference: "시편 19:14",
    text: "나의 반석이시요 나의 구속자이신 여호와여 내 입의 말과 마음의 묵상이 주의 앞에 열납되기를 원하나이다",
    theme: "말과 마음이 같은 곳을 향하기를" },
  { id: "v025", category: "words", reference: "잠언 16:24",
    text: "선한 말은 꿀송이 같아서 마음에 달고 뼈에 양약이 되느니라",
    theme: "말이 몸까지 낫게 함" },
  { id: "v026", category: "words", reference: "에베소서 4:29",
    text: "무릇 더러운 말은 너희 입 밖에도 내지 말고 오직 덕을 세우는데 소용되는대로 선한 말을 하여",
    theme: "세우는 말을 고르는 일" },
  { id: "v027", category: "words", reference: "야고보서 1:19",
    text: "사람마다 듣기는 속히 하고 말하기는 더디 하며 성내기는 더디 하라",
    theme: "먼저 듣는 순서" },
  { id: "v028", category: "words", reference: "시편 141:3",
    text: "여호와여 내 입 앞에 파수꾼을 세우시고 내 입술의 문을 지키소서",
    theme: "말을 참는 것도 도움이 필요한 일" },
  { id: "v029", category: "words", reference: "잠언 18:21",
    text: "죽고 사는 것이 혀의 권세에 달렸나니",
    theme: "말 한 마디의 무게" },
  { id: "v030", category: "words", reference: "골로새서 4:6",
    text: "너희 말을 항상 은혜 가운데서 소금으로 고루게 함같이 하라",
    theme: "말에 담기는 온도" },

  /* ---------- together : 함께 있음 ---------- */
  { id: "v031", category: "together", reference: "전도서 4:9",
    text: "두 사람이 한 사람보다 나음은 저희가 수고함으로 좋은 상을 얻을 것임이라",
    theme: "혼자보다 둘이 나음" },
  { id: "v032", category: "together", reference: "마태복음 18:20",
    text: "두세 사람이 내 이름으로 모인 곳에는 나도 그들 중에 있느니라",
    theme: "함께 있는 자리에 이미 계심" },
  { id: "v033", category: "together", reference: "로마서 12:15",
    text: "즐거워하는 자들로 함께 즐거워하고 우는 자들로 함께 울라",
    theme: "감정을 같이 겪는 일" },
  { id: "v034", category: "together", reference: "히브리서 13:5",
    text: "내가 과연 너희를 버리지 아니하고 과연 너희를 떠나지 아니하리라",
    theme: "떠나지 않겠다는 약속" },
  { id: "v035", category: "together", reference: "시편 133:1",
    text: "형제가 연합하여 동거함이 어찌 그리 선하고 아름다운고",
    theme: "같이 있는 것의 아름다움" },
  { id: "v036", category: "together", reference: "갈라디아서 6:2",
    text: "너희가 짐을 서로 지라 그리하여 그리스도의 법을 성취하라",
    theme: "짐을 나눠 지는 방식" },
  { id: "v037", category: "together", reference: "요한일서 4:19",
    text: "우리가 사랑함은 그가 먼저 우리를 사랑하셨음이라",
    theme: "먼저 받은 사랑에서 나오는 사랑" },
  { id: "v038", category: "together", reference: "잠언 17:17",
    text: "친구는 사랑이 끊어지지 아니하고 형제는 위급한 때까지 위하여 났느니라",
    theme: "끊어지지 않는 관계" },
  { id: "v039", category: "together", reference: "이사야 41:10",
    text: "두려워 말라 내가 너와 함께 함이니라 놀라지 말라 나는 네 하나님이 됨이니라",
    theme: "함께 있으니 두려워하지 않아도 됨" },
  { id: "v040", category: "together", reference: "시편 139:5",
    text: "주께서 나의 전후를 두르시며 내게 안수하셨나이다",
    theme: "앞뒤로 둘러싸여 있음" },

  /* ---------- restart : 다시 시작 ---------- */
  { id: "v041", category: "restart", reference: "예레미야애가 3:22",
    text: "여호와의 자비와 긍휼이 무궁하시므로 우리가 진멸되지 아니함이니이다",
    theme: "끝나지 않는 자비" },
  { id: "v042", category: "restart", reference: "예레미야애가 3:23",
    text: "이것이 아침마다 새로우니 주의 성실이 크도소이다",
    theme: "매일 아침 새로 시작됨" },
  { id: "v043", category: "restart", reference: "이사야 43:19",
    text: "보라 내가 새 일을 행하리니 이제 나타낼 것이라 너희가 그것을 알지 못하겠느냐",
    theme: "이미 시작된 새 일" },
  { id: "v044", category: "restart", reference: "빌립보서 3:13",
    text: "뒤에 있는 것은 잊어버리고 앞에 있는 것을 잡으려고",
    theme: "지나간 것을 놓아주기" },
  { id: "v045", category: "restart", reference: "잠언 24:16",
    text: "대저 의인은 일곱 번 넘어질지라도 다시 일어나려니와",
    theme: "넘어지는 횟수보다 일어나는 것" },
  { id: "v046", category: "restart", reference: "시편 37:24",
    text: "저는 넘어지나 아주 엎드러지지 아니함은 여호와께서 손으로 붙드심이로다",
    theme: "넘어져도 완전히 무너지지 않음" },
  { id: "v047", category: "restart", reference: "고린도후서 5:17",
    text: "이전 것은 지나갔으니 보라 새 것이 되었도다",
    theme: "이전 것에 매이지 않아도 됨" },
  { id: "v048", category: "restart", reference: "시편 51:10",
    text: "하나님이여 내 속에 정한 마음을 창조하시고 내 안에 정직한 영을 새롭게 하소서",
    theme: "마음이 새로 지어지기를" },
  { id: "v049", category: "restart", reference: "요엘 2:25",
    text: "내가 너희에게 갚아 주리라",
    theme: "잃은 시간에 대한 회복" },
  { id: "v050", category: "restart", reference: "빌립보서 1:6",
    text: "너희 속에 착한 일을 시작하신 이가 그리스도 예수의 날까지 이루실 줄을 우리가 확신하노라",
    theme: "시작한 이가 끝까지 마무리함" },

  /* ---------- joy : 감사와 기쁨 ---------- */
  { id: "v051", category: "joy", reference: "시편 118:24",
    text: "이 날은 여호와의 정하신 것이라 이 날에 우리가 즐거워하고 기뻐하리로다",
    theme: "오늘이라는 날 자체가 선물" },
  { id: "v052", category: "joy", reference: "데살로니가전서 5:18",
    text: "범사에 감사하라 이는 그리스도 예수 안에서 너희를 향하신 하나님의 뜻이니라",
    theme: "작은 일에서 감사를 찾는 연습" },
  { id: "v053", category: "joy", reference: "느헤미야 8:10",
    text: "여호와를 기뻐하는 것이 너희의 힘이니라",
    theme: "기쁨이 곧 힘이 됨" },
  { id: "v054", category: "joy", reference: "시편 126:5",
    text: "눈물을 흘리며 씨를 뿌리는 자는 기쁨으로 거두리로다",
    theme: "울며 뿌린 것이 기쁨으로 돌아옴" },
  { id: "v055", category: "joy", reference: "스바냐 3:17",
    text: "너로 인하여 기쁨을 이기지 못하시며 너를 잠잠히 사랑하시며 너로 인하여 즐거이 부르며 기뻐하시리라",
    theme: "나를 보며 기뻐하는 시선" },
  { id: "v056", category: "joy", reference: "시편 30:5",
    text: "저녁에는 울음이 기숙할지라도 아침에는 기쁨이 오리로다",
    theme: "밤이 지나면 오는 아침" },
  { id: "v057", category: "joy", reference: "잠언 17:22",
    text: "마음의 즐거움은 양약이라도 심령의 근심은 뼈로 마르게 하느니라",
    theme: "즐거움이 몸을 낫게 함" },
  { id: "v058", category: "joy", reference: "시편 100:2",
    text: "기쁨으로 여호와를 섬기며 노래하면서 그 앞에 나아갈지어다",
    theme: "무겁지 않게 나아가기" },
  { id: "v059", category: "joy", reference: "로마서 15:13",
    text: "소망의 하나님이 모든 기쁨과 평강을 믿음 안에서 너희에게 충만케 하사",
    theme: "채워지는 기쁨과 평안" },
  { id: "v060", category: "joy", reference: "시편 16:11",
    text: "주의 앞에는 기쁨이 충만하고 주의 우편에는 영원한 즐거움이 있나이다",
    theme: "이미 가득 차 있는 기쁨" }

];

